version: '3.8'

services:
  compute:
    image: devopsdockeruh/scaling-exercise-compute
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80
    depends_on:
      - calculator

  calculator:
    image: devopsdockeruh/scaling-exercise-calculator

  load-balancer:
    image: load-balancer
    build: .
    ports:
      - "8081:80"
    environment:
      - DEFAULT_HOST=localhost  # 👈 THIS IS THE MAGIC KEY!
    depends_on:
      - compute