import { createSlice } from '@reduxjs/toolkit'
import anecdoteService from './services/anecdotes'

const anecdoteSlice = createSlice({
  name: 'anecdotes',
  initialState: [],
  reducers: {
    createVote(state, action) {
      const id = action.payload
      const anecdoteToChange = state.find(n => n.id === id)
      if (anecdoteToChange) {
        anecdoteToChange.votes += 1
      }
    },
    appendAnecdote(state, action) {
      state.push(action.payload)
    },
    setAnecdotes(state, action) {
      return action.payload
    }
  }
})

// These are the internal actions generated by the slice
export const { createVote, appendAnecdote, setAnecdotes } = anecdoteSlice.actions

// THESE ARE THE THUNKS - Make sure these are exported correctly!
export const initializeAnecdotes = () => {
  return async dispatch => {
    const anecdotes = await anecdoteService.getAll()
    dispatch(setAnecdotes(anecdotes))
  }
}

export const createNewAnecdote = (content) => {
  return async dispatch => {
    const newAnecdote = await anecdoteService.createNew(content)
    dispatch(appendAnecdote(newAnecdote))
  }
}
export const voteAnecdote = (id) => {
  return async (dispatch, getState) => {
    // 1. Find the anecdote we want to change from the current state
    const anecdoteToVote = getState().anecdotes.find(n => n.id === id)
    
    // 2. Create a copy with one more vote
    const changedAnecdote = { 
      ...anecdoteToVote, 
      votes: anecdoteToVote.votes + 1 
    }

    // 3. Send it to the server
    const updatedAnecdote = await anecdoteService.update(id, changedAnecdote)
    
    // 4. Update the Redux store with the server's response
    // We can reuse the setAnecdotes logic or create a specific update action
    // For now, let's just refresh the whole list from the state logic 
    // or use a map in a new reducer action.
    dispatch(setAnecdotes(getState().anecdotes.map(a => a.id !== id ? a : updatedAnecdote)))
  }
}
export default anecdoteSlice.reducer