version: '3.8'

services:
  web-service:
    image: devopsdockeruh/simple-web-service
    container_name: web-server-dashboard
    ports:
      - "8080:8080"
    command: server
    # Exercise 2.2 finished