services:
  backend:
    build: ./example-backend
    ports:
      - "8080:8080"
    container_name: compose-backend
    environment:
      - REQUEST_ORIGIN=http://localhost:5001
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./example-backend:/usr/src/app # 👈 Binds backend source code folder

  frontend:
    build:
      context: ./example-frontend
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8080
    ports:
      - "5001:80"
    container_name: compose-frontend
    volumes:
      - ./example-frontend:/usr/src/app # 👈 Binds frontend source code folder

  redis:
    image: redis:7-alpine
    container_name: compose-redis

  postgres:
    image: postgres:15-alpine
    container_name: compose-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data: